[2024-06-13T14:29:50.026+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T14:29:50.041+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T14:28:32.281398+00:00 [queued]>
[2024-06-13T14:29:50.047+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T14:28:32.281398+00:00 [queued]>
[2024-06-13T14:29:50.048+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T14:29:50.058+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_model_task> on 2024-06-13 14:28:32.281398+00:00
[2024-06-13T14:29:50.067+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=22164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T14:29:50.068+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'test_model_task', 'manual__2024-06-13T14:28:32.281398+00:00', '--job-id', '495', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmpjo83qfye']
[2024-06-13T14:29:50.069+0000] {standard_task_runner.py:63} INFO - Started process 22182 to run task
[2024-06-13T14:29:50.069+0000] {standard_task_runner.py:91} INFO - Job 495: Subtask test_model_task
[2024-06-13T14:29:50.097+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.test_model_task manual__2024-06-13T14:28:32.281398+00:00 [running]> on host 33b4ab31339c
[2024-06-13T14:29:50.154+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='test_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T14:28:32.281398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T14:28:32.281398+00:00'
[2024-06-13T14:29:50.155+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T14:29:50.745+0000] {logging_mixin.py:188} INFO -  1/17 ━━━━━━━━━━━━━━━━━━━━ 3s 201ms/step
[2024-06-13T14:29:50.796+0000] {logging_mixin.py:188} INFO -  9/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step  
[2024-06-13T14:29:50.982+0000] {logging_mixin.py:188} INFO - 17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[2024-06-13T14:29:50.983+0000] {logging_mixin.py:188} INFO - 17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[2024-06-13T14:29:50.999+0000] {logging_mixin.py:188} INFO - 521
[2024-06-13T14:29:51.018+0000] {warnings.py:112} WARNING - /opt/***/dags/demo_***.py:259: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data1['predict'] = y_test_predict  # thêm dữ liệu

[2024-06-13T14:29:51.305+0000] {logging_mixin.py:188} INFO - Độ phù hợp tập test: 0.9376919809993537
[2024-06-13T14:29:51.306+0000] {logging_mixin.py:188} INFO - Sai số tuyệt đối trung bình trên tập test (VNĐ): 716.4357305662188
[2024-06-13T14:29:51.307+0000] {logging_mixin.py:188} INFO - Phần trăm sai số tuyệt đối trung bình tập test: 0.010361996615003567
[2024-06-13T14:29:51.367+0000] {logging_mixin.py:188} INFO - 1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[2024-06-13T14:29:51.368+0000] {logging_mixin.py:188} INFO - 1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[2024-06-13T14:29:51.376+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T14:29:51.376+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T14:29:51.382+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=stock_prediction, task_id=test_model_task, run_id=manual__2024-06-13T14:28:32.281398+00:00, execution_date=20240613T142832, start_date=20240613T142950, end_date=20240613T142951
[2024-06-13T14:29:51.412+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T14:29:51.429+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T14:29:51.431+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
